[build]
  publish = "."           # Serve index.html from repo root
  functions = "netlify/functions"  # Directory where Netlify looks for functions

[build.environment]
  PYTHON_VERSION = "3.10"  # Supported Python runtime for functions

[functions]
  # Presence of this section enables Python functions
