[build]
  # Install Python dependencies so the convert function can run.
  command = "pip install -r requirements.txt"
  publish = "./"
  functions = "netlify/functions"
[build.environment]
  PYTHON_VERSION="3.10.8"

[functions]
  included_files = ["final.py"]
