[build]
  command   = "pip install -r requirements.txt"
  publish   = "."
  functions = "netlify/functions"

[functions]
  directory      = "netlify/functions"
  included_files = ["final.py"]

[dev]
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10.8"
