[build]
  # The site is purely static, so no build command is needed. Netlify will
  # automatically bundle Python functions when present.
  publish = "./"
  functions = "netlify/functions"
[build.environment]
  PYTHON_VERSION="3.10.8"

[functions]
  included_files = ["final.py"]
